
---
version: "3"

volumes:
  traefik_acme_data: {}
  local_postgres_data: {}

services:
  traefik:
    build:
      context: .
      dockerfile: ./dockerfiles/traefik/Dockerfile
    image: mlflow_production_traefik
    restart: always
    volumes:
      - traefik_acme_data:/etc/traefik/acme/
      - ./config/.htpasswd:/etc/traefik/.htpasswd:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
    ports:
      - "0.0.0.0:80:8081"
      - "0.0.0.0:443:8443"


  mlflow:
    build:
      context: .
      dockerfile: ./dockerfiles/mlflow/Dockerfile
    image: mlflow_production_server
    restart: always
    command: /start
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:11.8
    restart: always
    env_file:
      - .env
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
