---
tls:
  # certificates:
  #   - certFile: "/etc/certs/local-cert.pem"
  #     keyFile: "/etc/certs/local-key.pem"
  #     stores:
  #       - default

  # stores:
  #   default:
  #     defaultCertificate:
  #       certFile: "/etc/certs/local-cert.pem"
  #       keyFile: "/etc/certs/local-key.pem"

  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites: # use only elliptic curve (the strongest) ciphers
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
