---
- name: Provision
  hosts: all
  become: true

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  # Need docker and docker-compose install from python to work with community docker compose
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose


  # Taken from https://github.com/geerlingguy/ansible-role-docker/blob/master/molecule/default/converge.yml
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization.  # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  tasks:
    - block:
        - name: Ensure Postgres apt key is present
          apt_key:
            url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

        - name: Ensure Postgres apt repo is present
          apt_repository:
            repo: "deb http://apt.postgresql.org/pub/repos/apt \
              {{ ansible_distribution_release }}-pgdg main"
          notify: Update apt cache

        - name: Install required packages
          apt:
            name:
              - postgresql
              - gettext
              - apache2-utils
            state: present
            update_cache: true
            cache_valid_time: 600
            autoremove: true
            autoclean: true
      become: true

  handlers:
    - name: Update apt cache
      become: true
      apt:
        update_cache: true
