collections:
  - name: community.docker

roles:
  - name: geerlingguy.pip
    src: https://github.com/geerlingguy/ansible-role-pip

  - name: geerlingguy.docker
    src: https://github.com/geerlingguy/ansible-role-docker
