---
- name: Run
  hosts: all
  gather_facts: no
  become: true

  tasks:
    - name: Copy repository to remote servers
      copy:
        src: ../
        dest: /home/ubuntu/mlflow-production-docker
        force: true #overwrite if modified

    - name: Create and start services
      community.docker.docker_compose:
        project_src: /home/ubuntu/mlflow-production-docker
        remove_orphans: true
        build: true
        files:
          - production.yml
      register: output


    - ansible.builtin.debug:
        var: output
